### ISSUE TITLE
机器人可以不可以手动设置服务器地址

### ISSUE THREAD

**Issue by gb000000001** [trueai-org/midjourney-proxy#12]
试了一下，好像机器人直接链接的是discord官网，可不可以手动设置反向代理的网址。

**Comment by trueai-org** [comment]
目前暂时没有指定机器人的代理地址，我后续添加一下

**Comment by trueai-org** [comment]
![image](https://github.com/user-attachments/assets/649343b4-c7af-4bff-84fc-e738d92596b8)

**Comment by trueai-org** [comment]
已修复
