### ISSUE TITLE
短期内如果描述词相同，获取到的图片有概率会混同

### ISSUE THREAD

**Issue by gb000000001** [trueai-org/midjourney-proxy#13]
短期内如果提交的描述词相同，获取到的图片有概率会混同。没有正确的获得返回的图片，将两个不同的提交获得相同的图片。

**Comment by gb000000001** [comment]
discord里面是正常的

**Comment by gb000000001** [comment]
奇怪的是临时预览图片是正常的，就结果图片会混同成一个

**Comment by trueai-org** [comment]
是的，目前会存在这个问题，其他的中转api也会存在此问题。
因为discord的消息机制，在消息处理和通信时很大程度上并不会把原始消息的id以及none携带，且在多种消息混合时带来复杂性。并且niji与mj消息传递的机制也会有细则区别。
因此目前的方案，当上下文无法通过唯一标识获取正在执行的作业时，会通过内容匹配

**Comment by trueai-org** [comment]
因此会导致上述的问题。
针对以上问题，我曾经使用 bot 和user的双重确认标识，但仍然会存在问题。
计划的解决方案: 保证的并行的作业当 prompt 相同时，在额外的频道处理。
即: 增加子频道处理此问题。
预计1周内上线此方案。

**Comment by gb000000001** [comment]
感谢大佬

**Comment by trueai-org** [comment]
因为update消息由bot确认的，而最终消息由 bot和user双重确认的因此可能产生上述问题

**Comment by gb000000001** [comment]
之前用的GoAmzAI: [https://github.com/Licoy/GoAmzA](https://github.com/Licoy/GoAmzAI)他家的自带的mj代理，没有这个问题，你要不咨询下他是如何匹配消息的，我看你的介绍页有，你们应该都认识。

**Comment by trueai-org** [comment]
触发这个是概率问题，当后入的队列提前完成了，可能就会出现此问题。匹配规则也是根据内容匹配的

**Comment by trueai-org** [comment]
目前的双重确认也存在 bug，我这边处理一下

**Comment by trueai-org** [comment]
已修复，请使用 v2.6.9 版本
