### ISSUE TITLE
生成图片进度卡在85%

### ISSUE THREAD

**Issue by xinglicai** [trueai-org/midjourney-proxy#2]
生成图片进度卡在85%，实际上midjounery很早就生成好了图片，请问可能的原因会是什么
![Uploading 微信图片_20240719142014.png…]()

**Comment by trueai-org** [comment]
消息确认是由 BOT 机器人确认消息的，目前根据消息日志查看， Bot 机器人没有收到消息确认，仅仅收到了 Update 的消息，
由此可以推断，BOT 机器人在这期间可能离线了，因为 BOT 后面有恢复日志。

使用 BOT 机器人的目的是高可用，可能的优化方案为，当用户或 BOT 任意一方收到确认通知时，即：表示已完成。这样可以保证消息的高可用，避免可能出现的问题。

> BOT 仅收到了 update 消息
![image](https://github.com/user-attachments/assets/066d9d62-cf69-429e-a04a-f9dda471d88e)

> BOT 重连了
![image](https://github.com/user-attachments/assets/edddcb0b-4554-4514-8d42-29d16402299c)

**Comment by trueai-org** [comment]
目前已处理，请使用 v2.3.2 最新版
