### ISSUE TITLE
修改token的时候要尝试好多次才能修改成功

### ISSUE THREAD

**Issue by gb000000001** [trueai-org/midjourney-proxy#20]
token改变，修改token的时候要尝试好多次才能修改成功

**Comment by trueai-org** [comment]
token 改变需要重启容器

**Comment by trueai-org** [comment]
或者重启程序的。
后期这个token管理，将会优化为账户体系，分别为：管理员和用户、访客等身份，预计2周内。

**Comment by gb000000001** [comment]
现在是只要user token发生变化这个账号的所有设置都改不了了，想不启用也修改不了

**Comment by trueai-org** [comment]
不太明白，usertoken 与设置没有关系呀，你说的是管理员 token 吗？有报错或者截图没

**Comment by trueai-org** [comment]
请升级最新版
