### ISSUE TITLE
请问这个私信ID怎么获取

### ISSUE THREAD

**Issue by JokerBlog** [trueai-org/midjourney-proxy#21]
<img width="462" alt="image" src="https://github.com/user-attachments/assets/2fec4c2c-ab87-420c-9dd4-60d81c5edebc">

请问这个私信ID怎么获取

**Comment by trueai-org** [comment]
右键机器人，点击消息，就进入私信了

**Comment by JokerBlog** [comment]
您能给我截图一下吗？我进入私信了，我不知道ID怎么获取，有个图例我就懂了，谢谢❤️

**Comment by trueai-org** [comment]
url 上的就是私信 ID.
![image](https://github.com/user-attachments/assets/0e700957-af3e-4c42-994d-4080c42d3242)
