### ISSUE TITLE
只有放大（U）的图片拉不过来

### ISSUE THREAD

**Issue by liuyu14752** [trueai-org/midjourney-proxy#22]
discord正常，变换(V)正常，在mj-proxy里面报错如下：
![11111](https://github.com/user-attachments/assets/8c49ad7a-2179-4c06-b5e5-62a420970dc8)

**Comment by trueai-org** [comment]
已修复

**Comment by trueai-org** [comment]
使用最新版

**Comment by liuyu14752** [comment]
已更新，问题修复，谢谢！
