### ISSUE TITLE
请问这个二次放大对应的API接口是什么？

### ISSUE THREAD

**Issue by tanshiqi** [trueai-org/midjourney-proxy#28]
![CleanShot 2024-08-08 at 00 18 08](https://github.com/user-attachments/assets/81458ff0-7f28-4d9d-a0d4-835c8a04af12)
请问这个二次放大对应的API接口是什么？文档里没有找到

**Comment by trueai-org** [comment]
![chrome_Dmx401iAGc](https://github.com/user-attachments/assets/e7916934-2504-4fc4-b972-3b8eb44e93b3)

**Comment by trueai-org** [comment]
点击这里，看下调用参数。
