### ISSUE TITLE
垫图的图片可不可以上传oss然后引用oss的图片进行绘画

### ISSUE THREAD

**Issue by cmswat** [trueai-org/midjourney-proxy#29]
垫图的图片可不可以上传oss然后引用oss的图片进行绘画，目前是上传到discord的，感觉不是很稳定。垫图是可以直接用外链的。

**Comment by trueai-org** [comment]
近期没有规划，可能要晚点

**Comment by trueai-org** [comment]
v3.7.0 已经支持，可以测试是否满足需求

**Comment by trueai-org** [comment]
如果直接使用国内链接，可能引发其他问题。参考：https://github.com/trueai-org/midjourney-proxy/issues/32

**Comment by cmswat** [comment]
太感谢了

**Comment by cmswat** [comment]
现在是上传到oss引用了吗
