### ISSUE TITLE
角色参考或风格参考如果使用国内的cdn图片会导致触发人工校验

### ISSUE THREAD

**Issue by Seedsa** [trueai-org/midjourney-proxy#32]
如果上传的参考图是国内的cdn外链(未开启全球加速)，会导致提交任务一直卡主(在处理将cdn图片上传到midjourney cdn导致提交任务的请求时间变长)，这时候会大概率触发cloudflare校验。

 建议提供接口将图片上传到discord cdn，然后使用discordcdn的链接作为参考图

**Comment by trueai-org** [comment]
感谢，会考虑加入

**Comment by trueai-org** [comment]
v3.7.0 已经支持

**Comment by cmswat** [comment]
太感谢
