### ISSUE TITLE
3.5.1 版本配置代理无法连接socket 导致无可用账号实例

### ISSUE THREAD

**Issue by HaQiuqiu** [trueai-org/midjourney-proxy#35]
配置代理在2.3.0版本可以正常使用, 在3.5.1版本配置代理失效 导致无法连接sockets
<img width="1149" alt="截屏2024-08-14 下午3 59 10" src="https://github.com/user-attachments/assets/188d0ac5-35fa-4404-bf81-cb6dc74a1133">

**Comment by trueai-org** [comment]
3.5.1 版本，代理通过 gui 再配置一下

**Comment by HaQiuqiu** [comment]
大佬,我在GUI没有代理配置入口呀

**Comment by HaQiuqiu** [comment]
> 3.5.1 版本，代理通过 gui 再配置一下

我翻遍了侧边栏...
大佬,我在GUI没有代理配置入口呀

**Comment by trueai-org** [comment]
![image](https://github.com/user-attachments/assets/70a2ca9f-7793-4a0e-9681-a48452e23bfc)

**Comment by HaQiuqiu** [comment]
copy . 
     还有一个小问题. 3.5.1  user admin token配置不生效 = 密码错误 ..    无论配置什么 登录都只能输入:admin
<img width="1149" alt="截屏2024-08-14 下午4 11 17" src="https://github.com/user-attachments/assets/f04d4f53-2411-4e4e-9b31-330f2a3c6201">

**Comment by trueai-org** [comment]
3.x 版本后，所有的配置，都使用 GUI 配置的。
token 通过用户管理配置

**Comment by trueai-org** [comment]
登录后重置 admin token
