### ISSUE TITLE
上传图片到discord的时候都会带有一串消息，把这个删除了会不会影响效果

### ISSUE THREAD

**Issue by cmswat** [trueai-org/midjourney-proxy#37]
上传图片到discord的时候上面都会带有一串文件名称，把这个删除了会不会影响正常使用，测试了一下好像不影响。
![image](https://github.com/user-attachments/assets/a9d3e9a4-30e1-412b-8fe9-5c735d6382d1)

**Comment by trueai-org** [comment]
不影响
