### ISSUE TITLE
Добавите ли midjourney Editor

### ISSUE THREAD

**Issue by bigclawBin** [trueai-org/midjourney-proxy#43]
https://youtu.be/n4apjbyNfGE

**Comment by trueai-org** [comment]
The website join is already being planned

**Comment by bigclawBin** [comment]
А планируется добавление функции расширение фото?

**Comment by trueai-org** [comment]
Gallery function? There are no plans at the moment.

**Comment by bigclawBin** [comment]
нет расширение фотографий

**Comment by bigclawBin** [comment]
планируется ли?

**Comment by trueai-org** [comment]
Hello, please speak English，I don't understand

**Comment by bigclawBin** [comment]
Are you planning to add a photo extension? That is, the editor function

**Comment by trueai-org** [comment]
https://ai.trueai.org/#/draw-test
Thank you very much. You mean add a drawing editor to the drawing page?


This project only provides api services, and does not provide a complete drawing interaction function for the time being.


---

If needed, you can try the following clients

Recommended Clients
ChatGPT-Midjourney: https://github.com/Licoy/ChatGPT-Midjourney

Easily set up your own ChatGPT+StabilityAI+Midjourney web service -> https://chat-gpt-midjourney-96vk.vercel.app/#/mj
Visit the website -> Settings -> Custom API -> Model (Midjourney) -> API Address -> https://ai.trueai.org/mj
ChatGPT Web Midjourney Proxy: https://github.com/Dooy/chatgpt-web-midjourney-proxy

Visit https://vercel.ddaiai.com/ -> Settings -> MJ Drawing API Address -> https://ai.trueai.org/
GoAmzAI: https://github.com/Licoy/GoAmzAI

Access backend -> Drawing Management -> Add -> MJ Drawing API Address -> https://ai.trueai.org/mj
