### ISSUE TITLE
用这套程序可以避免账号被封禁吗

### ISSUE THREAD

**Issue by 2016geek** [trueai-org/midjourney-proxy#44]

**Comment by trueai-org** [comment]
调整参数，不高频绘图，基本不会封号。

作图频繁预防警告

任务间隔 30~180 秒，执行前间隔 3.6 秒以上
每日最大 200 张
每日工作时间，建议 9：10~22：50
如果有多个账号，则建议开启垂直领域功能，每个账号只做某一类作品
