### ISSUE TITLE
重绘Vary(Region)和 custom Zoom功能没反应

### ISSUE THREAD

**Issue by MingwieJin** [trueai-org/midjourney-proxy#52]
重绘Vary(Region)和custom Zoom功能，一直进度是0没有反应

![image](https://github.com/user-attachments/assets/aae9a01d-6887-47f5-9967-d89e4ce67345)

这个应该怎么弄呢

**Comment by trueai-org** [comment]
群里已回答

**Comment by MingwieJin** [comment]
解决了以后回来记录一下，帮助有缘人

感觉是在前端系统调用的时候（不是本项目自带的后台），返回没有设置好cors头导致的问题，所以前端尽量需要proxy代理到后端然后再请求api接口。

至于为啥cors不太正确，查了一下不知道是不是这个原因导致的
![image](https://github.com/user-attachments/assets/96009fb1-fb1b-44f6-93ec-179ddf70ef47)
![image](https://github.com/user-attachments/assets/f640ae2d-5fe3-42ac-a1a4-7b575fa83b5d)

坐等c#大神解答哈
