### ISSUE TITLE
在国内服务器使用出现问题

### ISSUE THREAD

**Issue by gb000000001** [trueai-org/midjourney-proxy#54]
在国内服务器使用出现问题，即使设置了反向代理的服务器，程序还是会链接discord.com这个域名，而不是反向代理的域名

**Comment by gb000000001** [comment]
<img width="308" alt="微信图片_20241015130114" src="https://github.com/user-attachments/assets/1d2308b6-a834-453b-a0da-bcdf87164eff">
就是在这里设置的，但是好像不管用

**Comment by trueai-org** [comment]
在国内要配置有2种方案。
1、Proxy 配置，你自己的代理配置。
2、Discord 配置，discord 代理配置。

**Comment by trueai-org** [comment]
配置完后要重启服务才会生效
