### ISSUE TITLE
图生图卡75%

### ISSUE THREAD

**Issue by xinglicai** [trueai-org/midjourney-proxy#6]
[image](https://github.com/user-attachments/assets/a82816a4-a9a0-4c63-b4ba-da60ad61e6e0)
大佬，文生图不卡85%，图生图卡75%了
![image](https://github.com/user-attachments/assets/0885dee7-b876-4109-8a29-8007569b0bcd)

**Comment by trueai-org** [comment]
v2.3.3 刚刚修复

**Comment by trueai-org** [comment]
使用最新版再试下，重新优化了匹配规则
