### ISSUE TITLE
[BUG] 图像生成接口 无法上传Base64垫图

### ISSUE THREAD

**Issue by hibikico** [trueai-org/midjourney-proxy#61]
如题，只要图像生成时涉及垫图上传，就100%触发这个Bug

不带垫图的任务可以正常执行

![image](https://github.com/user-attachments/assets/d772fb7a-d5a0-4502-956f-a2cac27e5fec)
![image](https://github.com/user-attachments/assets/e17de61f-ea86-4e0a-b708-943cf4c49231)

Bug提交日期： 2024年 11月 10日
docker镜像版本： `v5.12.0`

**Comment by trueai-org** [comment]
请通过系统配置，启用用户上传功能
![image](https://github.com/user-attachments/assets/99f494ad-7d40-407e-b935-b57cd34b5c4f)

**Comment by hibikico** [comment]
这个开关部署时就已经启用了，提交这个issue时也确认此开关是打开状态

![image](https://github.com/user-attachments/assets/41ebd65c-fd44-48ca-9319-db4c6404c17d)

不过在重启docker容器后此问题解决

建议在设置页面中添加一个重启实例的功能，可以防止类似配置不生效的问题发生

**Comment by hibikico** [comment]
可能不是一个Bug，刚刚发现如果Discord账号风控被限制上传文件也会导致这个问题：
![image](https://github.com/user-attachments/assets/d22521f3-15ad-4503-9040-281b751acbf7)

**Comment by trueai-org** [comment]
遇到这种情况，还是尽量人工处理好点
