### ISSUE TITLE
[Feature] 增加Cloudflare R2对象存储服务支持

### ISSUE THREAD

**Issue by hibikico** [trueai-org/midjourney-proxy#63]
CF R2是个S3兼容的对象存储服务，性价比较高，无出口流量费用，提供免费额度，易于设置。

**Comment by trueai-org** [comment]
你好， S3 只有 10G 免费存储吗？
如果只有 10G，那么只能存储 2000张不到的图片，接入的意义不大

**Comment by hibikico** [comment]
不是哥们，真商用肯定是会掏钱的啊，S3对象存储服务，只要掏钱，存储空间都是无限给用的

另外光是R2全球存储+无出站流量费用就已经很厉害了，存储价格本身也比阿里云低，综合来看，CF R2的对象存储服务性价比和成本可控性吊打阿里云的那个什么oss，阿里云oss不仅存储贵，流量费也上天，要是万一有个用户逮到一个url恶意刷一刷那流量费直接原地破产

**Comment by hibikico** [comment]
还有最近Discord上传垫图太多会很容易触发Discord风控（触发Discord Spam触发然后踢掉线 ），听说不要上传垫图到Discord，上传到对象存储就会不会轻易风控了

看到目前虽然看到最近有接入阿里的对象存储，但是阿里云那东西是真不敢用，阿里云随随便便被用户刷一刷直接来个上万的欠费账单的案例网上看过太多了

**Comment by trueai-org** [comment]
R2: 每 GB 收取 $0.015 的存储费用，每 100 GB，为 10.6 RMB.
阿里云：每 100 GB，14元。

存储费用比阿里云低一些，我这这边测试下。

**Comment by trueai-org** [comment]
v6.0.0-beta.6
