### ISSUE TITLE
[BUG] Unable to submit prompts/tasks

### ISSUE THREAD

**Issue by DucLocNewMoon** [trueai-org/midjourney-proxy#64]
For the last 10 days or so, we have been unable to submit prompts/tasks and the system gives back this error. If able, can you help us explain what is wrong? Tell us how we can help so that we can debug this together.

![image](https://github.com/user-attachments/assets/c7f3755a-c7f6-4c72-acf5-4e312c976ac8)

**Comment by trueai-org** [comment]
1, first make sure your account is enabled, and second make sure you have mj drawing turned on
![image](https://github.com/user-attachments/assets/589c022b-81b1-404b-9538-635cf1f08a5b)
![image](https://github.com/user-attachments/assets/8c9074b1-9409-452f-b929-62b33dd9c371)

**Comment by DucLocNewMoon** [comment]
I made sure all of the above are enabled/turned on and reproduce the error, it still happened.
![image](https://github.com/user-attachments/assets/93003066-650c-4be6-bdfd-949603f556cf)

![image](https://github.com/user-attachments/assets/107d774e-606e-426d-95a0-078f394a4510)

![image](https://github.com/user-attachments/assets/ccb15280-af9a-4f8e-9e93-800474fec929)

**Comment by trueai-org** [comment]
The previous version may have bugs. You can try to upgrade the latest version

**Comment by trueai-org** [comment]
This is configured incorrectly because you enabled vertical domains but did not select which domains
![image](https://github.com/user-attachments/assets/24c66be8-13bd-4d06-98e7-d63b8c35b7bf)

**Comment by DucLocNewMoon** [comment]
Wow, I turned that off and it worked again, thank you! Since the issue is resolved, should I close this or you guys?

**Comment by trueai-org** [comment]
Thank you for your support. I'll just close it
