### ISSUE TITLE
访问绘画接口怎么走设置的用户令牌

### ISSUE THREAD

**Issue by erenboss** [trueai-org/midjourney-proxy#69]
本地部署windows版本
请求接口：/mj/submit/imagine
发现并没有需要验证用户令牌，如何开启这个设置

**Comment by erenboss** [comment]
![QQ图片20241224155434](https://github.com/user-attachments/assets/17c26b61-fe4a-4223-86f2-e50e17e3d406)
关闭这2个请求就变成Authorization header missing.

**Comment by erenboss** [comment]
![image](https://github.com/user-attachments/assets/5bfb4d84-3d7e-45a6-b333-567131b725d9)

**Comment by erenboss** [comment]
Authorization header missing.

**Comment by trueai-org** [comment]
不需要 bearea ，参考公益站点。

**Comment by erenboss** [comment]
但是我关闭访客和关闭注册后接口就调不通了

**Comment by erenboss** [comment]
开启访客模式不是就暴露了吗

**Comment by trueai-org** [comment]
不需要 bearer 前缀，明白不

**Comment by trueai-org** [comment]
![image](https://github.com/user-attachments/assets/c3411ed8-6cd9-44af-b958-99c93b916672)
看 swagger

**Comment by erenboss** [comment]
好的好的，抱歉，没看到这个
