### ISSUE TITLE
是不是缺少一个图片储存到本地

### ISSUE THREAD

**Issue by CN-Jayden** [trueai-org/midjourney-proxy#7]
使用国外服务器搭建，在国内打开使用，生成的图片无法查看

**Comment by trueai-org** [comment]
计划会添加本地存储支持，计划可能在2周后添加。

**Comment by trueai-org** [comment]
已经添加支持了。

![image](https://github.com/user-attachments/assets/577d7c49-2f62-4e59-8076-e63b5f26260c)
