### ISSUE TITLE
ApiSecret不起效果

### ISSUE THREAD

**Issue by Recho-design** [trueai-org/midjourney-proxy#8]
填写ApiSecret后，ChatGPT Web Midjourney Proxy端请求头中出现了Mj-Api-Secret但内容和ApiSecret不一致也能生图

不填写ApiSecret可以成功调用并生图，填写ApiSecret就是以上的问题，在web端随意填写key都可以调用

在midjourney-proxy的后台进行生图测试时，Mj-Api-Secret的内容是空白

我应该怎样给api添加key呢，本人比较小白，请指教

**Comment by trueai-org** [comment]
请求头添加：`Authorization` 或 `Mj-Api-Secret` 是等价的，如果配置了任意一个，只要其中一个有效的，就可以绘图。
如果：UserToken 或 AdminToken，都没有设定，则不限制绘图认证。
```
  "UserToken": "", // 用户绘画令牌 token，可以用来访问绘画接口，可以不用设定
  "AdminToken": "", // 管理后台令牌 token，可以用来访问绘画接口和管理员账号等功能
```

**Comment by trueai-org** [comment]
注意，不要开启 Demo 模式，DEMO 用于演示模式，演示模式下，不使用令牌也可以请求绘图的。

**Comment by Recho-design** [comment]
感谢回复，我的appsettings.Production.json配置文件大致填写如下，填写了UserToken也没有效果？在ChatGPT Web Midjourney Proxy随意填写了api secret也成功生图了
```{
  "Demo": null, // 网站配置为演示模式
  "UserToken": "888888",
  "AdminToken": "", // 管理后台令牌 token，可以用来访问绘画接口和管理员账号等功能
  "mj": {
    "AccountChooseRule": "BestWaitIdle", // BestWaitIdle | Random | Weight | Polling
    "Discord": {
      "GuildId": "126521729*****",
      "ChannelId": "126521729*****",
      "PrivateChannelId": "1256495659***", // MJ 私信频道 ID，用来接受 seed 值
      "NijiBotChannelId": "1261608644***", // NIJI 私信频道 ID，用来接受 seed 值
      "UserToken": "*******",
      "BotToken": "******",
      "UserAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36",
      "Enable": false,
      "CoreSize": 3,
      "QueueSize": 10,
      "MaxQueueSize": 100,
      "TimeoutMinutes": 5,
      "Mode": "FAST", // RELAX | FAST | TURBO 指定生成速度模式 --fast, --relax, or --turbo parameter at the end.
      "Weight": 1
    },
    "NgDiscord": {
      "Server": "",
      "Cdn": "",
      "Wss": "",
      "ResumeWss": "",
      "UploadServer": ""
    },
    "Proxy": {
      "Host": "",
      "Port": 10809
    },
    "Accounts": [],
    "BaiduTranslate": {
      "Appid": "", // your_appid
      "AppSecret": "" // your_app_secret
    },
    "Openai": {
      "GptApiUrl": "", // your_gpt_api_url
      "GptApiKey": "", // your_gpt_api_key
      "Timeout": "00:00:30",
      "Model": "gpt-3.5-turbo",
      "MaxTokens": 2048,
      "Temperature": 0
    },
    "TranslateWay": "NULL", // NULL | GTP | BAIDU
    "ApiSecret": "888888", 
    "NotifyHook": "", // your_notify_hook
    "NotifyPoolSize": 10
  },
  "Serilog": {
    "MinimumLevel": {
      "Default": "Information",
      "Override": {
        "Default": "Warning",
        "System": "Warning",
        "Microsoft": "Warning"
      }
    },
    "WriteTo": [
      {
        "Name": "File",
        "Args": {
          "path": "logs/log.txt",
          "rollingInterval": "Day",
          "fileSizeLimitBytes": null,
          "rollOnFileSizeLimit": false,
          "retainedFileCountLimit": 31
        }
      },
      {
        "Name": "Console"
      }
    ]
  },
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*",
  "urls": "http://*:8080"
}
```

**Comment by trueai-org** [comment]
要配置一下管理员 token，因为 token 为空时 = 管理员 token。因此认为是管理员。

**Comment by Recho-design** [comment]
都设定了token还是不起作用
  "UserToken": "888888",
  "AdminToken": "999999", 
  "ApiSecret": "777777",
  
  代理后台测试：
  
![1](https://github.com/user-attachments/assets/b7f0715d-ba18-42d7-b0c4-8e3d61113276)


web后台测试：
![Uploading 2.jpg…]()

**Comment by trueai-org** [comment]
你是否有多个appsetting配置文件

**Comment by trueai-org** [comment]
确保，appsettings.Production.json 这个是有效的，修改后重启下容器

**Comment by Recho-design** [comment]
没有其他的配置文件了，每次修改都重启过
![3](https://github.com/user-attachments/assets/24104f4d-cd37-4d64-aef9-76f2a24a2e73)
![4](https://github.com/user-attachments/assets/454f9037-6b05-444b-84af-e73e72ce1b85)

**Comment by trueai-org** [comment]
那么肯定是appsetting编码问题了，确保是unix编码格式，可以使用nodepad++查看文件编码

**Comment by Recho-design** [comment]
我在服务器和本地都看了一下，应该是unix？
![5](https://github.com/user-attachments/assets/918ee548-6c79-404f-a8df-6f2ba807e966)
![6](https://github.com/user-attachments/assets/ef9aa2cc-67de-4bc4-b3e9-550b3d60ff36)

**Comment by trueai-org** [comment]
再确认下，后台能否登录。
![image](https://github.com/user-attachments/assets/e669dbbc-bd00-474d-86da-58d0d12fe820)

**Comment by trueai-org** [comment]
登录后确认是否为 admin
![image](https://github.com/user-attachments/assets/c2c42f92-15f5-47fd-b094-676e095b732d)

**Comment by Recho-design** [comment]
后台可以登录，且输入正确的密码才能以admin身份登入

**Comment by trueai-org** [comment]
那就是说明配置是有效的。
你的环境变量中，没有配置 DEMO 吧？

**Comment by trueai-org** [comment]
经过多次测试，不输入  token 的话，一定是返回 401 的
![image](https://github.com/user-attachments/assets/ce603f70-a858-4361-865d-78cfc4c9df21)

**Comment by trueai-org** [comment]
判断是否开启 demo，如果使用 空 密码，可以登录，说明开启了 demo 模式。

**Comment by Recho-design** [comment]
现在正常了！docker启动时复制的第三步的代码，导致环境变量加了 `-e DEMO=true \`没有注意到，修改后正确运行了
非常感谢🙏
